POST http://localhost:3333/api/links
Content-Type: application/json

{
"code": "seat1",
"url": "https://rocketseat.com.br"
}

###

GET localhost:3333/api/links

###

GET localhost:3333/seat

###

GET localhost:3333/api/metrics
