version: '3.8'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shortlinks
    volumes:
      - postgres_data:/bitnami/postgres/data
    ports:
      - '5432:5432'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  redis_data:
